version: '3.8'

networks:
  frontend:
    driver: bridge
  backend:

services:
  solawi-bid_frontend:
    build:
      context: .
      dockerfile: solawi-bid-frontend/docker/Dockerfile
    ports:
      - "8080:80"
    container_name: solawi-bid_frontend
    hostname: solawi-bid_frontend
    env_file:
      - solawi-bid-frontend/.env

    depends_on:
      - solawi-bid_backend
    networks:
      - frontend
      - backend
  solawi-bid_backend:
    build:
      context: .
      dockerfile: solawi-bid-backend/docker/Dockerfile
    ports:
      - "8081:8081"
    container_name: solawi-bid_backend
    hostname: solawi-bid_backend
    env_file:
      - solawi-bid-backend/.env
    depends_on:
      - solawi-bid_database
    networks:
       - backend

  solawi-bid_database:
    build:
      context: .
      dockerfile: solawi-bid-database/docker/Dockerfile
    container_name: solawi-bid_database
    hostname: solawi-bid_database
    ports:
      - "3306:3306"
    env_file:
      - solawi-bid-database/.env
    networks:
      - backend


 # adminer:
 #   image: adminer
 #   hostname: adminer
#    restart: always
 #   ports:
 #   - "8082:8080"
 #   networks:
 #     - frontend
 #     - backend
