name: Set Env Vars
description: Collect all files needed to run the application
inputs:
  #baseFolder:
  #  description: base folder for deployment
  #  required: true
  environment:
    description: Env
    required: true
  #frontendUrl:
  #  description: Env
  #  required: true
  #frontendPort:
  #  description: Env
  #  required: true
  #backendUrl:
  #  description: Env
  #  required: true
  #backendPort:
  #  description: Env
  #  required: true

  appOwnerUsername:
    description: Env
    required: true
  appOwnerPassword:
    description: Env
    required: true

  jwtSecret:
    description: Env
    required: true
  jwtRealm:
    description: Env
    required: true
  jwtDomain:
    description: Env
    required: true
  jwtAudience:
    description: Env
    required: true

  databaseDriver:
    description: Env
    required: true
  databaseUser:
    description: Env
    required: true
  databaseUrl:
    description: Env
    required: true
runs:
  using: composite
  steps:
    - name: Database
      shell: bash
      run: |
        echo "Hello Database"
    - name: Backend
      shell: bash
      run: |
        sed -i 's/ENVIRONMENT/${{inputs.environment}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        
        sed -i 's/JWT_AUDIENCE/${{inputs.jwtAudience}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/JWT_DOMAIN/${{inputs.jwtDomain}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/JWT_REALM/${{inputs.jwtRealm}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/JWT_SECRET/${{inputs.jwtSecret}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        
        sed -i 's/DATABASE_DRIVER/${{inputs.databaseDriver}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/DATABASE_URL/${{inputs.databaseUrl}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/DATABASE_USER/${{inputs.databaseUser}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        
        sed -i 's/APPLICATION_OWNER_USERNAME/${{inputs.appOwnerUsername}}/' solawi-bid-backend/build/resources/main/application.conf.dist
        sed -i 's/APPLICATION_OWNER_PASSWORD/${{inputs.appOwnerPassword}}/' solawi-bid-backend/build/resources/main/application.conf.dist
    
        cat solawi-bid-backend/build/resources/main/application.conf.dist
