name: Restart Application
description: Restart application
inputs:
  user:
    description: ""
    required: true
  pw:
    description: ""
    required: true
  
runs:
  using: composite
  steps:
    - name: Restart
      if: false
      shell: bash
      run: |
         cd /home/solawi-bid
         docker-compose down --remove-orphans  # Stop running containers
         docker-compose up --build -d  # Rebuild and restart containers
         docker system prune -f  # Cleanup unused Docker images
    - name: Get Info
      shell: bash
      run: |
        whoami
        set timeout -1
        set user "${{ inputs.user }}"
        set password "${{ inputs.pw }}"

        spawn su - $user
        expect "Password:"
        send "$password\r"
        interact
        
        sudo fail2ban-client status sshd
        cat /etc/ssh/sshd_config
