name: Set Env Vars
description: Collect all files needed to run the application
inputs:
  #baseFolder:
  #  description: base folder for deployment
  #  required: true
  environment:
    description: Env
    required: true
  mysqlUser:
    description: Env
    required: true
  mysqlDatabase:
    description: Env
    required: true
  mysqlPassword:
    description: Env
    required: true
  mysqlRootPassword:
    description: Env
    required: true
runs:
  using: composite
  steps:

    - name: Frontend
      shell: bash
      run: |
        touch solawi-bid-database/e.env
        chmod 644 solawi-bid-database/e.env
        echo "ENVIRONMENT=${{inputs.environment}}">>solawi-bid-database/e.env
        echo "MYSQL_USER=${{inputs.mysqlUser}}">>solawi-bid-database/e.env
        echo "MYSQL_PASSWORD=${{inputs.mysqlPassword}}">>solawi-bid-database/e.env
        echo "MYSQL_ROOT_PASSWORD=${{inputs.mysqlRootPassword}}">>solawi-bid-database/e.env
        echo "MYSQL_DATABASE=${{inputs.mysqlDatabase}}">>solawi-bid-database/e.env
        
