name: Build Frontend and Test
description: Build frontend and run all tests
runs:
  using: composite
  steps:
    - name: Check changes
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          frontend:
             - "solawi-bid-frontend/**"
             - "solawi-bid-api-data/**"
             - ".github/**"
             - "gradle" 

    - name: Build frontend without tests
      shell: bash
      run: ./gradlew solawi-bid-frontend:build -x test
      if: steps.changes.outputs.frontend == 'true'
