name: Build Backend and Test
description: Build backend and run all tests
runs:
  using: composite
  steps:
    - name: Build backend without tests
      shell: bash
      run: ./gradlew solawi-bid-backend:build -x test

    - name: Run unit tests
      uses: ./.github/actions/test
      with:
        testSuite: unitTest
        reportName: Unit
      if: always()
    - name: Run schema tests
      uses: ./.github/actions/test
      with:
        testSuite: schemaTest
        reportName: Schema
      if: always()
    - name: Run db functional tests
      uses: ./.github/actions/test
      with:
        testSuite: dbFunctionalTest
        reportName: DbFunctional
      if: always()
    - name: Run api tests
      uses: ./.github/actions/test
      with:
        testSuite: apiTest
        reportName: Api
      if: always()