name: CI Pipeline
on:
  workflow_dispatch:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # Use Eclipse Temurin distribution of OpenJDK
          java-version: '21'        # Specify the Java version you need, e.g., 8, 11, 17, etc.

      # Set up Gradle (necessary for caching and dependency installation)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'  # Or specify a version, like '7.5'

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Run unit tests
        run: ./gradlew unitTest
      - name: Run schema tests
        run: ./gradlew dbSchemaTest
      - name: Run dbFunctional tests
        run: ./gradlew dbFunctionalTest
      - name: Run api tests
        run: ./gradlew apiTest
      - name: Upload api test report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: solawi-bid-backend/build/reports/tests/apiTest
      - name: Display api test results
        run: |
          echo "## Api Test Report"
          echo "See detailed reports here: [Api Test Report](solawi-bid-backend/build/reports/tests/apiTest/index.html)"    
