name: CI Pipeline
on:
  workflow_dispatch:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # Use Eclipse Temurin distribution of OpenJDK
          java-version: '21'        # Specify the Java version you need, e.g., 8, 11, 17, etc.

      # Set up Gradle (necessary for caching and dependency installation)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'  # Or specify a version, like '7.5'

      # Cache Gradle dependencies for faster builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build backend without tests
        run: ./gradlew solawi-bid-backend:build -x test

      - name: Run unit tests
        uses: ./.github/actions/test
        with:
          testSuite: unitTest
          reportName: Unit
        if: always()
      - name: Run schema tests
        uses: ./.github/actions/test
        with:
          testSuite: schemaTest
          reportName: Schema
        if: always()
      - name: Run db functional tests
        uses: ./.github/actions/test
        with:
          testSuite: dbFunctionalTest
          reportName: Db Functional
        if: always()
      - name: Run api tests
        uses: ./.github/actions/test
        with:
          testSuite: apiTest
          reportName: Api
        if: always()