name: Nightly Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC daily

concurrency:
  group: database-backup
  cancel-in-progress: false

jobs:
  backup-database:
    runs-on: solyton
    steps:
      - name: Try To Dump the Database
        run: |
          mv -f ${{vars.DATABASE_NIGHTLY_BACKUP}} ${{vars.DATABASE_NIGHTLY_BACKUP}}.bak
          docker exec solawi-bid_database mysqldump -u${{vars.DATABASE_NIGHTLY_BACKUP}} -p${{secrets.MYSQL_PASSWORD}} ${{vars.MYSQL_DATABASE}} > ${{vars.DATABASE_DUMP }}

          if [ $? -ne 0 ]; then
            echo "Database dump failed!"
            exit 1
          fi

      - name: On Success Delete Old Backup
        if: success()
        run: |
          rm -f ${{vars.DATABASE_NIGHTLY_BACKUP}}.bak

      - name: On Failure Keep Old Backup
        if: failure()
        run: |
          echo "Backup failed, retaining old backup."
          mv -f ${{vars.DATABASE_NIGHTLY_BACKUP}}.bak ${{vars.DATABASE_NIGHTLY_BACKUP}}
