name: CI Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - devops/SMA-145/setup-workflow
    #paths-ignore:
    #  - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: self-hosted #jupiter #ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Setup JDK, Gradle and Caches
      #  uses: ./.github/actions/setup




      - name: Build
        run: ./gradlew build -x test

      - name: Test rsync
        run: |
          rsync -avr -e 'ssh -p --delete ${{ secrets.SOLYTON_SSH_PORT }}' ./ ${{ vars.SOLYTON }}



      #- name: Debug - List files
      #  run: |
      #    ls


      #- name: Run Backend tests
      #  uses: ./.github/actions/test-backend

      #- name: Run Frontend tests
      #  uses: ./.github/actions/test-frontend